name: "Bug report"
description: "Report a bug to help us improve."
title: "[BUG] <short description>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## Describe the bug"
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug here."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## To Reproduce"
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: |
        Please complete the following information:
        OS: [e.g. Linux]
        Java version: [e.g. 17]
        Game version: [e.g. 0.0.1.alpha1]
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
